index:
    path: /
    controller: App\Controller\DefaultController::index

home:
    path: /home
    controller: App\Controller\DefaultController::home
    
otra:
    path: /otra
    controller: App\Controller\DefaultController::otra
